---
sudo: required
language: python
python: 2.7

services:
  - docker

cache: pip

virtualenv:
  system_site_packages: false

jobs:
  include:
    - stage: install dependencies
      script:
        - pip install --upgrade setuptools
        - pip install ome-ansible-molecule/
    - stage: test
      script: cd ansible-role-basedeps && ../scripts/test.sh
    - stage: test
      script: cd ansible-role-basedeps && ../scripts/test.sh
    - stage: test
      script: cd ansible-role-haproxy && ../scripts/test.sh
    - stage: test
      script: cd ansible-role-ice && ../scripts/test.sh
    - stage: test
      script: cd ansible-role-java && ../scripts/test.sh
    - stage: test
      script: cd ansible-role-nginx && ../scripts/test.sh
    - stage: test
      script: cd ansible-role-omego && ../scripts/test.sh
    - stage: test
      script: cd ansible-role-omero-common && ../scripts/test.sh
    - stage: test
      script: cd ansible-role-postgresql && ../scripts/test.sh
    - stage: test
      script: cd ansible-role-ssl-certificate && ../scripts/test.sh
    - stage: test
      script: cd ansible-role-versioncontrol-utils && ../scripts/test.sh
